language: rust
sudo: true
os:
    - linux
dist: trusty

branches:
    only:
        - master

services:
    - docker

rust:
    - stable
    - nightly
    - 1.26.0

script:
    - cargo build --verbose
    - cargo test --verbose


addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev

# Coverage report
# Upload docs
after_success:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
            wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
            tar xzf v33.tar.gz && mkdir kcov-33/build && cd kcov-33/build && cmake .. && make &&
            sudo make install && cd ../.. &&
            file=`find target/debug -maxdepth 1 -executable -name "crups*"` &&
            kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov $file &&
            bash <(curl -s https://codecov.io/bash) &&
            echo "Uploaded code coverage"
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
            cargo doc --no-deps &&
            echo "<meta http-equiv=refresh content=0;url=crusp/index.html>" > target/doc/index.html &&
            git clone https://github.com/davisp/ghp-import.git &&
            ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
            echo "Uploaded documentation"
        fi
