(function() {var implementors = {};
implementors["crusp"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"crusp/variables/handlers/macros/enum.VarIndexType.html\" title=\"enum crusp::variables::handlers::macros::VarIndexType\">VarIndexType</a>",synthetic:false,types:["crusp::variables::handlers::macros::VarIndexType"]},{text:"impl&lt;Var:&nbsp;<a class=\"trait\" href=\"crusp/variables/trait.Variable.html\" title=\"trait crusp::variables::Variable\">Variable</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"crusp/variables/handlers/macros/struct.VarView.html\" title=\"struct crusp::variables::handlers::macros::VarView\">VarView</a>&lt;Var&gt;",synthetic:false,types:["crusp::variables::handlers::macros::VarView"]},{text:"impl&lt;Var:&nbsp;<a class=\"trait\" href=\"crusp/variables/trait.Variable.html\" title=\"trait crusp::variables::Variable\">Variable</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"crusp/variables/handlers/macros/struct.ArrayOfVarsView.html\" title=\"struct crusp::variables::handlers::macros::ArrayOfVarsView\">ArrayOfVarsView</a>&lt;Var&gt;",synthetic:false,types:["crusp::variables::handlers::macros::ArrayOfVarsView"]},{text:"impl&lt;Var:&nbsp;<a class=\"trait\" href=\"crusp/variables/trait.Variable.html\" title=\"trait crusp::variables::Variable\">Variable</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"crusp/variables/handlers/macros/struct.ArrayOfRefsView.html\" title=\"struct crusp::variables::handlers::macros::ArrayOfRefsView\">ArrayOfRefsView</a>&lt;Var&gt;",synthetic:false,types:["crusp::variables::handlers::macros::ArrayOfRefsView"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"crusp/variables/enum.VariableState.html\" title=\"enum crusp::variables::VariableState\">VariableState</a>",synthetic:false,types:["crusp::variables::VariableState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"crusp/variables/struct.VariableId.html\" title=\"struct crusp::variables::VariableId\">VariableId</a>",synthetic:false,types:["crusp::variables::VariableId"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
